version: '3'
services:
  lb:
    image: nginx
    ports:
    - "80:80"
    volumes:
    - ./nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
  app1:
    image: nginx
    ports:
    - "8080:80"
    volumes:
    - ./index-red.html:/usr/share/nginx/html/index.html:ro
  app2:
    image: nginx
    ports:
    - "8081:80"
    volumes:
    - ./index-green.html:/usr/share/nginx/html/index.html:ro
  app3:
    image: nginx
    ports:
    - "8082:80"
    volumes:
    - ./index-blue.html:/usr/share/nginx/html/index.html:ro
