version: '3.8'
services:
  # PostgreSQL
  postgresql:
    build: 
      context: ./postgresql/
      dockerfile: Dockerfile
    image: postgresql
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgresql/postgresql_data:/var/lib/postgresql/data
  # adminer
  adminer:
    build: 
      context: ./adminer/
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "8001:8080"
      
  # GraphQL
  node:
    image: node:19
    environment:
        - DEBUG=app:*
    tty: true
    ports:
        - '4000:4000'
    volumes:
        - ./node/src:/app
    working_dir: /app
    command: sh -c 'npx tsc; npm run dev'