version: '3.8'
services:
  # PostgreSQL
  postgresql:
    build: 
      context: ./postgresql/
      dockerfile: Dockerfile
    image: postgresql
    container_name: postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./postgresql/postgresql_data:/var/lib/postgresql/data
  # adminer
  adminer:
    build: 
      context: ./adminer/
      dockerfile: Dockerfile
    image: adminer
    container_name: adminer
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "8001:8080"